In [1]:
import pandas as pd
import gmaps
import requests
from config import g_key

In [2]:
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Kodiak,US,2021-10-20 18:51:36,57.7900,-152.4072,42.31,87,90,8.05
1,1,Upernavik,GL,2021-10-20 18:51:15,72.7868,-56.1549,33.17,99,100,13.91
2,2,Ikalamavony,MG,2021-10-20 18:55:01,-21.1500,46.5833,68.77,79,89,4.45
3,3,Atuona,PF,2021-10-20 18:51:04,-9.8000,-139.0333,77.22,80,49,13.96
4,4,Busselton,AU,2021-10-20 18:50:51,-33.6500,115.3333,51.04,79,96,14.65

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
gmaps.configure(api_key=g_key)

In [5]:
locations = city_data_df[["Lat","Lng"]]
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
fig = gmaps.figure()
fig
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
locations = city_data_df[["Lat","Lng"]]
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
fig = gmaps.figure()
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [7]:
locations = city_data_df[["Lat","Lng"]]
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
locations = city_data_df[["Lat","Lng"]]
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
#Temperate input
min_temp = float(input("What is the minimum temperature you would like?"))
max_temp = float(input("What is the maximum temperature you would like?"))

What is the minimum temperature you would like?75
What is the maximum temperature you would like?90

In [11]:
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
3,3,Atuona,PF,2021-10-20 18:51:04,-9.8000,-139.0333,77.22,80,49,13.96
9,9,Santa Isabel Do Rio Negro,BR,2021-10-20 18:55:04,-0.4139,-65.0192,86.29,66,100,2.10
10,10,San Patricio,US,2021-10-20 18:55:05,28.0170,-97.5169,87.89,52,40,5.41
14,14,Kassala,SD,2021-10-20 18:55:06,15.4510,36.4000,89.11,24,9,9.60
17,17,Kuala Terengganu,MY,2021-10-20 18:55:08,5.3302,103.1408,78.75,94,20,4.61
19,19,Belize,BZ,2021-10-20 18:55:09,17.2500,-88.7500,84.52,97,91,4.05
22,22,Kavali,IN,2021-10-20 18:55:10,14.9167,79.9833,82.99,72,42,3.49
23,23,Bethel,US,2021-10-20 18:49:20,41.3712,-73.4140,76.89,53,1,1.01
34,34,Sinnamary,GF,2021-10-20 18:55:13,5.3833,-52.9500,83.08,73,39,9.42
39,39,San Vicente,AR,2021-10-20 18:51:07,-26.6167,-54.1333,77.85,31,12,1.86

In [12]:
preferred_cities_df.count()

City_ID       184
City          184
Country       184
Date          184
Lat           184
Lng           184
Max Temp      184
Humidity      184
Cloudiness    184
Wind Speed    184
dtype: int64

In [13]:
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]]
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

C:\Users\wcat1\anaconda3\envs\PythonData\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

                         City Country  Max Temp      Lat       Lng Hotel Name
3                      Atuona      PF     77.22  -9.8000 -139.0333
9   Santa Isabel Do Rio Negro      BR     86.29  -0.4139  -65.0192
10               San Patricio      US     87.89  28.0170  -97.5169
14                    Kassala      SD     89.11  15.4510   36.4000
17           Kuala Terengganu      MY     78.75   5.3302  103.1408
19                     Belize      BZ     84.52  17.2500  -88.7500
22                     Kavali      IN     82.99  14.9167   79.9833
23                     Bethel      US     76.89  41.3712  -73.4140
34                  Sinnamary      GF     83.08   5.3833  -52.9500
39                San Vicente      AR     77.85 -26.6167  -54.1333

In [14]:
params = {
    "radius": 5000,
    "types": "lodging",
    "key":g_key,
    "location":"28.0170, -97.5169"}

base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
hotels = requests.get(base_url, params=params).json()
hotels

{'html_attributions': [],
 'results': [{'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0303008, 'lng': -97.52967430000001},
    'viewport': {'northeast': {'lat': 28.0316450302915,
      'lng': -97.52878091970851},
     'southwest': {'lat': 28.0289470697085, 'lng': -97.53147888029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Motel 6 Sinton, TX',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 618,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/109196991724611481040">Motel 6 Sinton, TX</a>'],
     'photo_reference': 'Aap_uEAV3sFY9PjffPM0zzlAd62Y9jOSgopYKPf0DAAB4MWx7Ax5s__ng17NmkrIZqCBxz7BsLuufG-v2587QgkrZ5JXILyel-hXaIN6GX4ad9FvJ5bTT-OHTBcP-zwDNjhWa_8MkueJUMALHXKSahIqKN_SyglMCXSUhrUk_rCDqCBrza6i',
     'width': 826}],
   'place_id': 'ChIJC_s3LHpsaIYRpKSMHhJMpSA',
   'plus_code': {'compound_code': '2FJC+44 Sinton, TX, USA',
    'global_code': '76W42FJC+44'},
   'rating': 3.4,
   'reference': 'ChIJC_s3LHpsaIYRpKSMHhJMpSA',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 294,
   'vicinity': '8154 U.S. 77, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.03519429999999, 'lng': -97.5096438},
    'viewport': {'northeast': {'lat': 28.0365399802915,
      'lng': -97.50810551970851},
     'southwest': {'lat': 28.03384201970849, 'lng': -97.51080348029151}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Economy Inn',
   'photos': [{'height': 2039,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103429624662089276453">Jeremy Kimball</a>'],
     'photo_reference': 'Aap_uEC6PH_UD4HsqL6CHfmf9qyld-58Fl1OB98g-t3bgONMwAuj0yToi9KtcpYU7x1h2bq1zIs0QfcEocHvlJSn9uQh3hDsbUeujLWIWOjVkW0ijscWjhL7cHUao51E7CPOIL8oe8XGm9HUGs4LxH6Clx71xWtyUwqkLKn7Rw9NUAvvu6e0',
     'width': 2268}],
   'place_id': 'ChIJSZqxp5BraIYRehQZaHWYrqU',
   'plus_code': {'compound_code': '2FPR+34 Sinton, TX, USA',
    'global_code': '76W42FPR+34'},
   'rating': 3.4,
   'reference': 'ChIJSZqxp5BraIYRehQZaHWYrqU',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 22,
   'vicinity': '202 S Vineyard St, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0275648, 'lng': -97.50478129999999},
    'viewport': {'northeast': {'lat': 28.0289094302915,
      'lng': -97.50339696970849},
     'southwest': {'lat': 28.0262114697085, 'lng': -97.5060949302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Tovar Estates',
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/110490788019747604260">Michael Conn</a>'],
     'photo_reference': 'Aap_uEB8xfqY69CdirhLj_R-no8mUndMsS2sqJ-Etpu3O0XeVTQzQ2DsIQZAJiNHS-glmQ3ApnClaJKy31U-HP6KoRNwH_bGH-l924EjsAkdfutTvJbCm_P33wmum9uWNYefCqoBKA1ehdnMlJG9brH0QBLsoEkPvESOUBM4Gh6PZLwqrzTh',
     'width': 4032}],
   'place_id': 'ChIJObDNDL9raIYRYhxojUI2WpE',
   'plus_code': {'compound_code': '2FHW+23 Sinton, TX, USA',
    'global_code': '76W42FHW+23'},
   'reference': 'ChIJObDNDL9raIYRYhxojUI2WpE',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': 'Sodville Road, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0285823, 'lng': -97.52950510000001},
    'viewport': {'northeast': {'lat': 28.0299203302915,
      'lng': -97.5286836197085},
     'southwest': {'lat': 28.0272223697085, 'lng': -97.53138158029152}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Americas Best Value Inn Sinton',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 1294,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/115373936219591984118">Americas Best Value Inn Sinton</a>'],
     'photo_reference': 'Aap_uEDtWQW22dspy68hRxUCsPbUWXQN48qWybRpsJfGEGQz26cINqmlqrmo3c4sncN8DLss2UEWyz_S8rIA7g-iSpiKpywR2mLIti82t8k5YJt-amelyKT5iToBBd7IxGs97EXhGm15ki44_csDO0hXrWHHWozZOqP2KCKVgXztppWfc6o6',
     'width': 1642}],
   'place_id': 'ChIJfUEkVnFsaIYROMi16pnMQBM',
   'plus_code': {'compound_code': '2FHC+C5 Sinton, TX, USA',
    'global_code': '76W42FHC+C5'},
   'rating': 3.4,
   'reference': 'ChIJfUEkVnFsaIYROMi16pnMQBM',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 95,
   'vicinity': '8108 U.S. 77, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0041217, 'lng': -97.5046691},
    'viewport': {'northeast': {'lat': 28.0054757302915,
      'lng': -97.5035991197085},
     'southwest': {'lat': 28.0027777697085, 'lng': -97.5062970802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Sinton RV Park',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 3024,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/103605801234475122198">Sinton RV Park</a>'],
     'photo_reference': 'Aap_uEAWvZgD_yuIVxKgrDyy-ypSkOoUj3q1HYq6VgJMvwzjEcaFguT4q80e1PfGx_5I6nn7FuyecIXfBJgxD6kQVaEneCcHRrF1e8_bvQT0s1RjVTX2-80k_ukGHnOEpD3ovZGWqbAkbPHovoUEnH5EfHlSLnvV2Gq8iJSjeLfHNuNbuUrF',
     'width': 4032}],
   'place_id': 'ChIJa4nQ8uBraIYRFP9lUte6G60',
   'plus_code': {'compound_code': '2F3W+J4 Sinton, TX, USA',
    'global_code': '76W42F3W+J4'},
   'rating': 4.2,
   'reference': 'ChIJa4nQ8uBraIYRFP9lUte6G60',
   'scope': 'GOOGLE',
   'types': ['rv_park', 'lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 17,
   'vicinity': '7146 Farm to Market 2046, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0374679, 'lng': -97.52159879999999},
    'viewport': {'northeast': {'lat': 28.0384408302915,
      'lng': -97.5202520197085},
     'southwest': {'lat': 28.0357428697085, 'lng': -97.5229499802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Hitching Post RV Park',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 1536,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/113957620582954045264">Hitching Post RV Park</a>'],
     'photo_reference': 'Aap_uEBTf9KMtouf5EWEGWlU3PSeUp0MWuQZXQv-lDrTSrRV4gQZZ_uKg-7nKTA6lsp1GTFucyrkIfOcwULCHIR14yvBDadS1DqcdNSiUI7FHZJ7c4i5975x_fSTeZ3ljYYpL2m7eNwjcSzK9kIA6TzSCX7lYyzC8PxcgKSI6sM1WZBHbzBz',
     'width': 2048}],
   'place_id': 'ChIJ87mJVIZraIYRiyI3p1rt-r0',
   'plus_code': {'compound_code': '2FPH+X9 Sinton, TX, USA',
    'global_code': '76W42FPH+X9'},
   'rating': 4.1,
   'reference': 'ChIJ87mJVIZraIYRiyI3p1rt-r0',
   'scope': 'GOOGLE',
   'types': ['rv_park', 'lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 27,
   'vicinity': '900 West Sinton Street, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0395736, 'lng': -97.5172348},
    'viewport': {'northeast': {'lat': 28.0405951802915,
      'lng': -97.5158847197085},
     'southwest': {'lat': 28.0378972197085, 'lng': -97.5185826802915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Creekside RV Village',
   'opening_hours': {'open_now': False},
   'photos': [{'height': 1279,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/108919568078715264786">Creekside RV Village</a>'],
     'photo_reference': 'Aap_uEBdJx5z87NtqlDYi-1oEzlnJGn4ice916rsQFDujqW98NBT1QR6AKhm8kNx8X2WdKryHljjO91vuq8ZyDOjbfU5AXBks0a3yXCABX5Dz9FhHcI9o_7jBm3AVEAqgSZtFN0BRrzxGj1h-rB1gxopWXweuWNfy99VQcsnGiG1AzQ12k6y',
     'width': 1920}],
   'place_id': 'ChIJqYQX0O5raIYRzZJxDfYMhD4',
   'plus_code': {'compound_code': '2FQM+R4 Sinton, TX, USA',
    'global_code': '76W42FQM+R4'},
   'rating': 4.7,
   'reference': 'ChIJqYQX0O5raIYRzZJxDfYMhD4',
   'scope': 'GOOGLE',
   'types': ['rv_park', 'lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 24,
   'vicinity': '600 West Fulton Street, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0197095, 'lng': -97.54462749999999},
    'viewport': {'northeast': {'lat': 28.02105738029151,
      'lng': -97.54309376970849},
     'southwest': {'lat': 28.0183594197085, 'lng': -97.5457917302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Lacy Oak Short Term Rentals',
   'place_id': 'ChIJI3endVptaIYR5BSy95hSD9Q',
   'plus_code': {'compound_code': '2F94+V4 Sinton, TX, USA',
    'global_code': '76W42F94+V4'},
   'reference': 'ChIJI3endVptaIYR5BSy95hSD9Q',
   'scope': 'GOOGLE',
   'types': ['lodging', 'point_of_interest', 'establishment'],
   'vicinity': '7759 County Road 2431, Sinton'},
  {'business_status': 'OPERATIONAL',
   'geometry': {'location': {'lat': 28.0580425, 'lng': -97.5263748},
    'viewport': {'northeast': {'lat': 28.0593934302915,
      'lng': -97.52446726970848},
     'southwest': {'lat': 28.0566954697085, 'lng': -97.5271652302915}}},
   'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/v1/png_71/lodging-71.png',
   'icon_background_color': '#909CE1',
   'icon_mask_base_uri': 'https://maps.gstatic.com/mapfiles/place_api/icons/v2/hotel_pinlet',
   'name': 'Mesquite Haven RV Park',
   'opening_hours': {'open_now': True},
   'photos': [{'height': 960,
     'html_attributions': ['<a href="https://maps.google.com/maps/contrib/100821788619574935471">Mesquite Haven RV Park</a>'],
     'photo_reference': 'Aap_uECwiIwiDiqHT2IZDOBFnj65fOlziUMzVtAsbhG7ALKtEfkgeKGtFnqToRFWKQZgoM0pubzpwok2ppeTt8zv1_2ljH8bF_OTHGt2RtVpWuiT8S5Rwj7LVL519TFGS7jDPSTXozufXnGQQDDbw3VibPU16zPd-DY1oBrcLS1oxNBLm6xI',
     'width': 720}],
   'place_id': 'ChIJm57badltaIYRuu4i2rfRqFY',
   'plus_code': {'compound_code': '3F5F+6F Sinton, TX, USA',
    'global_code': '76W43F5F+6F'},
   'rating': 4.3,
   'reference': 'ChIJm57badltaIYRuu4i2rfRqFY',
   'scope': 'GOOGLE',
   'types': ['rv_park', 'lodging', 'point_of_interest', 'establishment'],
   'user_ratings_total': 35,
   'vicinity': '14145 U.S. 181, Sinton'}],
 'status': 'OK'}

In [19]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
        
     #Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
   # params["location"] = f"{lat},{lng}"
    #print(params)

In [20]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    try:
            hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel Not Found... Skipping.")

C:\Users\wcat1\anaconda3\envs\PythonData\lib\site-packages\pandas\core\indexing.py:1720: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.
Hotel Not Found... Skipping.

In [21]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

In [22]:
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [23]:
# Heatmap of percent humidity
locations = hotel_df[["Lat", "Lng"]]
humidity = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))